### ISSUE TITLE
TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by rafalradomski** [brettimus/quill-placeholder#3]
Hi when I using your code I have error:

```
TypeError: Cannot read property 'config' of undefined
    at http://local.com:9000/lib/quill/dist/quill.js:10230:40
```

It looks like quill library looking for some config in line: 10230

```
 if (!(value && value !== format.config["default"])) {
          formats[name] = null;
}
```

I'm using quill v0.20.0.

When I comment line 27 in your code, placeholder working, but without styling:

```
this.quill.formatText(0, placeholder.length, this.style);
```

**Comment by brettimus** [comment]
I'll look into it today! Thanks

—

**Comment by brettimus** [comment]
Hey I'm running out of time to look into this issue today. Will try again tomorrow.

I saw you also opened an issue on the quill repo (https://github.com/quilljs/quill/issues/469)

Did that resolve anything for you?

**Comment by rafalradomski** [comment]
Not but I mixed your code with https://github.com/ksivamuthu/quill-html-placeholder and it's working ;)

**Comment by brettimus** [comment]
Hey can you post the code that caused your error? I can't duplicate, and I'm also on Quill 0.20.0

**Comment by brettimus** [comment]
I updated the main repo with a working example too if that helps.

**Comment by brettimus** [comment]
alright - inability to replicate + the complete overhaul on the v1 branch means i'm going to close this.
